# Generated by Django 4.2.3 on 2023-07-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('food', 'food'), ('decoration', 'decoration'), ('supplies', 'supplies'), ('other', 'other')], default='supplies', max_length=250)),
                ('custom_item_name', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
