# Generated by Django 4.2.3 on 2023-07-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('budget', models.PositiveIntegerField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to='planner.attendee')),
                ('expenses', models.ManyToManyField(blank=True, related_name='events', to='planner.expense')),
                ('tasks', models.ManyToManyField(blank=True, related_name='events', to='planner.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planner.user')),
            ],
        ),
    ]
