# Generated by Django 4.2.3 on 2023-07-31 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_attendee_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='planner.attendee'),
        ),
    ]
